sudo: required
dist: trusty
language: scala
script:
  - if [[ "$TRAVIS_PULL_REQUEST" != false ]]; then sbt ++$TRAVIS_SCALA_VERSION test; else travis_retry sbt ++$TRAVIS_SCALA_VERSION test; fi
scala:
  - 2.11.8
jdk:
  - oraclejdk8
branches:
  only:
    # We're only building these branches and pull requests.
    - master
    - develop
notifications:
  slack: valtech-ons:nLeAGETA8HsuIi5fMQCaLe2G